// Generated by gencpp from file darknet_rospy_msgs/DarkBoxArray.msg
// DO NOT EDIT!


#ifndef DARKNET_ROSPY_MSGS_MESSAGE_DARKBOXARRAY_H
#define DARKNET_ROSPY_MSGS_MESSAGE_DARKBOXARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <darknet_rospy_msgs/DarkBox.h>

namespace darknet_rospy_msgs
{
template <class ContainerAllocator>
struct DarkBoxArray_
{
  typedef DarkBoxArray_<ContainerAllocator> Type;

  DarkBoxArray_()
    : header()
    , dark_array()  {
    }
  DarkBoxArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dark_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::darknet_rospy_msgs::DarkBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::darknet_rospy_msgs::DarkBox_<ContainerAllocator> >::other >  _dark_array_type;
  _dark_array_type dark_array;





  typedef boost::shared_ptr< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct DarkBoxArray_

typedef ::darknet_rospy_msgs::DarkBoxArray_<std::allocator<void> > DarkBoxArray;

typedef boost::shared_ptr< ::darknet_rospy_msgs::DarkBoxArray > DarkBoxArrayPtr;
typedef boost::shared_ptr< ::darknet_rospy_msgs::DarkBoxArray const> DarkBoxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_rospy_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/home/nvidia/catkin_ws/src/common_msg/sensor_msgs/msg'], 'geometry_msgs': ['/home/nvidia/catkin_ws/src/common_msg/geometry_msgs/msg'], 'darknet_rospy_msgs': ['/home/nvidia/catkin_ws/src/darknet_rospy/darknet_rospy_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "822841aecb4bb6b72d78b4ce5a699e44";
  }

  static const char* value(const ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x822841aecb4bb6b7ULL;
  static const uint64_t static_value2 = 0x2d78b4ce5a699e44ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_rospy_msgs/DarkBoxArray";
  }

  static const char* value(const ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
DarkBox[] dark_array\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: darknet_rospy_msgs/DarkBox\n\
string label\n\
float64 probability\n\
int64 xmin\n\
int64 ymin\n\
int64 xmax\n\
int64 ymax\n\
";
  }

  static const char* value(const ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dark_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DarkBoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_rospy_msgs::DarkBoxArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dark_array[]" << std::endl;
    for (size_t i = 0; i < v.dark_array.size(); ++i)
    {
      s << indent << "  dark_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::darknet_rospy_msgs::DarkBox_<ContainerAllocator> >::stream(s, indent + "    ", v.dark_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROSPY_MSGS_MESSAGE_DARKBOXARRAY_H
